name: Branch_1_Push

on:
  push:
    branches:
      - B1


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install pytest and pylint
      run: |
        pip install pytest
        pip install pylint

    - name: Run Pylint
      run: pylint add.py
