name: Branch_2_Push

on:
  push:
    branches:
      - B2


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install pylint
      run: |
        pip install pylint

    - name: Run Pylint
      run: pylint sub.py
